name: CI

on:
  push:
    branches:
      - master  # Ensuring it triggers on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create a mock .env file
        run: |
          echo "ENV=development" >> .env
          echo "API_KEY=your-api-key-here" >> .env

      - name: Run config script
        run: python config.py  # Running config.py to check environment variable loading

      - name: Run tests 
        run: |
          pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
